#ifndef Engine_Enums_h__
#define Engine_Enums_h__

namespace Engine
{
	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum ESHADER_TYPE {
		ST_POSTEX,
		ST_NORTEX,
		ST_NONANIM,
		ST_ANIM,
		ST_MESHINSTANCE,
		ST_EFFECTMESH,
		ST_EFFECTTEX,
		ST_PARTICLE,
		ST_TRAIL,
		ST_CUBE,
		ST_UIINSTANCE,
		ST_UI,
		ST_DEFERRED,
		ST_POSTPROCESS,
		ST_HDR,
		ST_COMPUTE,
		ST_FXAA,
		ST_DOF,
		ST_POINT,
		ST_END
	};

	enum ETEXTURE_TYPE
	{
		NONE,
		DIFFUSE,
		SPECULAR,
		AMBIENT,
		EMISSIVE,
		HEIGHT,
		NORMALS,
		SHININESS,
		OPACITY,
		DISPLACEMENT,
		LIGHTMAP,
		REFLECTION,
		BASE_COLOR,
		NORMAL_CAMERA,
		EMISSION_COLOR,
		METALNESS,
		DIFFUSE_ROUGHNESS,
		AMBIENT_OCCLUSION,
		SHEEN,
		CLEARCOAT,
		TRANSMISSION,
		UNKNOWN,
	};

	enum EASE_TYPE
	{
		EASE_LINEAR,
		EASE_IN_SINE, EASE_OUT_SINE, EASE_IN_OUT_SINE,
		EASE_IN_QUAD, EASE_OUT_QUAD, EAS_IN_OUT_QUAD,
		EASE_IN_CUBIC, EASE_OUT_CUBIC, EASE_IN_OUT_CUBIC,
		EASE_IN_QUART, EASE_OUT_QUART, EASE_IN_OUT_QUART,
		EASE_IN_QUINT, EASE_OUT_QUINT, EASE_IN_OUT_QUINT,
		EASE_IN_EXPO, EASE_OUT_EXPO, EASE_IN_OUT_EXPO,
		EASE_IN_CIRC, EASE_OUT_CIRC, EASE_IN_OUT_CIRC,
		EASE_IN_BACK, EASE_OUT_BACK, EASE_IN_OUT_BACK,
		EASE_IN_ELASTIC, EASE_OUT_ELASTIC, EASE_IN_OUT_ELASTIC,
		EASE_IN_BOUNCE, EASE_OUT_BOUNCE, EASE_IN_OUT_BOUNCE,
		EASE_END
	};

	enum EFADE
	{
		// IN : 밝아지는거, OUT : 어두워지는거
		FADE_NONE, FADE_IN, FADE_OUT
	};
	enum ESHAKEFLAG { SHAKE_NONE = 0, SHAKE_ROT = 1 << 0, SHAKE_LOC = 1 << 1, SHAKE_FOV = 1 << 2 };
	enum ESHAKEFUNC { SHAKE_WAVE, SHAKE_LINEAR };
	enum ESHAKETYPE { ROT, LOC, FOV, TYPE_END };
}

#endif // Engine_Enums_h__