#pragma once

#define UIMGR CUIMgr::GetInstance()
#define GETPOS GetTransform()->GetState(CTransform::STATE_POSITION)
#define ITEMMGR CItemMgr::GetInstance()
#define QUESTMGR CQuestMgr::GetInstance()
#define DIALOGUEMGR CDialogueMgr::GetInstance()

enum UI_LAYER {
	UI_LAYER_HUD = 0, UI_POPUP_MOVABLE = 1, UI_POPUP_FIXED = 2, UI_POPUP_FULL = 3,
	UI_LAYER_END = 4
};
enum UI_TYPE {
	UI_HUD = 0, UI_BAR = 1, UI_ICON = 2, UI_PROGRESS = 3, UI_SLIDER = 4, UI_BUTTON = 5, UI_SCROLLBG = 6,
	UI_SLOT = 7, UI_SCROLL = 8, UI_COOLTIME = 9, UI_UV = 10, UI_PANEL = 11, UI_BACKGROUND = 12, UI_BACKGROUND_R = 13,
	UI_HOVER = 14, UI_TOOLTIP = 15, UI_COVER = 16, UI_ITEMBG = 17, UI_ITEMICON = 18, UI_ITEMHOVER = 19, UI_ITEMTEXT = 20,
	UI_ITEMTAB = 21, UI_COVER_RV = 22/*Cover Reverse UpsideDown*/, UI_BACKGROUND_NT = 23/*Non Transparent*/, UI_TEXT = 24,
	UI_LOCKON = 25, UI_MONHP = 26, UI_MONINFO = 27, UI_HL = 28, UI_HR = 29, UI_INSTANCEITEMBG = 30, UI_INSTANCEITEMSLOT = 31,
	UI_INSTANCEITEMICON = 32, UI_INSTANCEITEMCOOLTIME = 33, UI_INSTANCEITEMHOVER = 34, UI_INSTANCEQUICKBG = 35,
	UI_INSTANCEQUICKMAINSLOT = 36, UI_INSTANCEQUICKITEMSLOT = 37, UI_INSTANCEQUICKCOMBATSLOT = 38, UI_INSTANCEQUICKFRAME = 39,
	UI_INSTANCEPARRING = 40, UI_INSTANCEABNORMALSLOT = 41, UI_INSTANCEWORLDHP = 42, UI_INSTANCEBOSSHP = 43, UI_NORMALTEXT = 44,
	UI_INSTANCEBOSSABNORMAL = 45, UI_INSTANCEQUEST = 46, UI_INSTANCEQUESTINDICATOR = 47, UI_INSTANCEINTERACTION = 48,
	UI_INSTANCEDIALOGUE = 49, UI_INSTANCECRAFTBG = 50, UI_INSTANCECRAFTHOVER = 51, UI_INSTANCECRAFTTAB = 52,
	UI_INSTANCECRAFTSLOT = 53, UI_INSTANCETRADEBG = 54, UI_INSTANCETRADESLOT = 55, UI_INSTANCETRADETAB = 56,
	UI_INSTANCETRADEHOVER = 57, UI_QUESTCOMPLETE = 58, UI_ITEMTOOLTIP = 59, UI_SPEECHBALLON = 60,
	UI_STARFORCE = 61, UI_OPTIONBG = 62, UI_OPTIONTAB = 63, UI_OPTIONHOVER = 64, UI_OPTIONSLIDER = 65, UI_OPTIONCHECKBOX = 66,
	UI_CROSSHAIR = 67, UI_INSTANCEWORLDNPC = 68, UI_TARGETINDICATOR = 69, UI_INTERACTIONSTATUE = 70, UI_ADENAMOUNT = 71,
	UI_CRAFTRESULT = 72, UI_TUTORIAL = 73, UI_INTERACTIONPOPUP = 74, UI_COUNTDOWN = 75, UI_MAPTITLE = 76,
	UI_SPRITEEFFECT = 77, UI_UVBAR = 78, UI_END,
};
enum UI_TEX_TYPE {
	UI_TEX_D = 0/*DIFFUSE*/, UI_TEX_DM = 1/*DIFFUSE&MASK*/, UI_TEX_M = 2/*COLOR&MASK*/, UI_TEX_NONE = 3/*NO TEX*/,
	UI_TEX_DMN = 4/*DIFFUSE&MASK&NOISE*/, UI_TEX_DN = 5/*DIFFUSE&NOISE*/, UI_TEX_N = 6/*COLOR&NOISE*/, UI_TEX_MN = 7/*MASK&NOISE*/,
	UI_NONE = 8, UI_TEX_END = 9,
};
enum UI_SLOT_TYPE {
	SLOT_MOUSE = 0, SLOT_INVEN = 1, SLOT_EQUIP = 2, SLOT_QUICK = 3, SLOT_SKILL = 4, SLOT_ABNORMAL = 5,
	SLOT_END = 6
};
enum UI_ITEM_TYPE {
	UI_ITEM_EQUIP = 0, UI_ITEM_USABLE = 1, UI_ITEM_REINFROCE = 2, UI_ITEM_CRAFT = 3, UI_ITEM_MISC = 4, UI_ITEM_END = 5,
};
enum ITEM_TYPE {
	ITEM_EQUIP = 0, ITEM_USABLE = 1, ITEM_REINFROCE = 2, ITEM_CRAFT = 3, ITEM_MISC = 4, ITEM_END = 5,
};
enum ITEM_EQUIP_TYPE {
	ITEM_EQUIP_HELMET = 0, ITEM_EQUIP_UPPER = 1, ITEM_EQUIP_LOWER = 2, ITEM_EQUIP_CAPE = 3, ITEM_EQUIP_GLOVE = 4, ITEM_EQUIP_BOOTS = 5,
	ITEM_EQUIP_END = 6,
};
enum ITEM_USABLE_TYPE {
	ITEM_USABLE_HP = 0, ITEM_USABLE_MP = 1, ITEM_USABLE_BUFF = 2, ITEM_USABLE_END = 3,
};
enum QUEST_TYPE {
	QUEST_MAIN = 0, QUEST_SUB0 = 1, QUEST_SUB1 = 2, QUEST_END = 3
};
enum CRAFT_SET_TAG {
	SET_PLATE_0 = 0, SET_PLATE_1 = 1, SET_PLATE_2 = 2, SET_PLATE_3 = 3, SET_CRAFT_END, 
};
enum DIALOGUE_STATE {
	DIALOGUE_START, DIALOGUE_PROCESSING, DIALOGUE_COMPLETE, DIALOGUE_DONE, DIALOGUE_END,
};

#define EFFECTMGR CEffectMgr::GetInstance() 
#define CHARACTERMGR CCharacterMgr::GetInstance()